version: '3.8.0'

services:
  mynote:
    image: andy1985stan/mynote:0.37.0
    container_name: mynote-v0.37.0
    ports:
      - "127.0.0.1:8080:9100"
    volumes:
      - ~/Documents/MyNote/database:/app/database
      - ~/Documents/MyNote/logs:/app/logs
      - ~/Documents/MyNote/media:/app/media
      - ~/Documents/MyNote/tmp:/app/tmp
      - ~/Documents/MyNote/uploads:/app/uploads
      - ~/Documents/MyNote/gemini_root:/root/.gemini
      - ~/Documents/MyNote/gemini_app:/app/.gemini
      - ~/Documents/MyNote/crontabs:/var/spool/cron/crontabs
    restart: unless-stopped
