services:
  mynote:
    image: andy1985stan/mynote:0.37.0
    container_name: mynote-v0.37.0
    ports:
      - "127.0.0.1:8080:9100"
    volumes:
      - ~/Documents/MyNoteL/database:/app/database
      - ~/Documents/MyNoteL/logs:/app/logs
      - ~/Documents/MyNoteL/media:/app/media
      - ~/Documents/MyNoteL/tmp:/app/tmp
      - ~/Documents/MyNoteL/uploads:/app/uploads
      - ~/Documents/MyNoteL/gemini_root:/root/.gemini
      - ~/Documents/MyNoteL/gemini_app:/app/.gemini
      - ~/Documents/MyNoteL/crontabs:/var/spool/cron/crontabs
    restart: unless-stopped
